In [18]:
import numpy as np

X = np.random.random((32, 10))
y = np.random.random((10,))

print(X)
print(y)

[[8.81577508e-01 2.82127617e-02 2.13290788e-01 8.62266475e-01
  9.12768196e-01 2.62251280e-01 2.20365237e-01 9.30739727e-01
  5.35411024e-02 2.22292739e-01]
 [1.32600031e-01 7.66486848e-01 1.54685410e-01 9.76191783e-01
  2.90958654e-01 8.86106501e-01 4.00918741e-01 7.26778348e-01
  3.95350186e-01 1.63665465e-01]
 [9.46272293e-01 4.63043010e-01 2.35018408e-01 8.84516719e-01
  7.89595800e-01 7.62300921e-01 6.51511487e-01 2.28825247e-01
  2.31529465e-01 2.90672657e-01]
 [1.59007888e-01 4.76269722e-01 9.79695818e-01 9.04992301e-01
  6.64304227e-01 2.25629071e-01 4.18692163e-02 8.95166097e-01
  2.58955685e-01 5.36434046e-01]
 [1.88352379e-01 3.28804610e-01 1.22885146e-01 1.85381368e-01
  6.45610035e-01 3.41634418e-01 3.14742360e-02 4.26608484e-01
  7.57503598e-02 4.21639486e-01]
 [9.94999063e-01 9.08944593e-01 6.45919251e-01 3.70536142e-01
  6.21358865e-01 6.96214453e-01 2.18418908e-01 4.83210303e-01
  8.31791379e-01 8.40153762e-01]
 [5.83351569e-01 3.75871926e-01 1.54762818e-01 6.35824236e

In [19]:
y = np.expand_dims(y, axis=0)

print(y, y.shape)

[[0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]] (1, 10)


In [20]:
Y = np.concatenate([y]*32, axis=0)

print(Y, Y.shape)


[[0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491 0.20714054 0.79388493 0.44631551]
 [0.0201785  0.67923956 0.35921296 0.13592868 0.73721015 0.70788157
  0.73640491

In [21]:
print(X, X.shape)

[[8.81577508e-01 2.82127617e-02 2.13290788e-01 8.62266475e-01
  9.12768196e-01 2.62251280e-01 2.20365237e-01 9.30739727e-01
  5.35411024e-02 2.22292739e-01]
 [1.32600031e-01 7.66486848e-01 1.54685410e-01 9.76191783e-01
  2.90958654e-01 8.86106501e-01 4.00918741e-01 7.26778348e-01
  3.95350186e-01 1.63665465e-01]
 [9.46272293e-01 4.63043010e-01 2.35018408e-01 8.84516719e-01
  7.89595800e-01 7.62300921e-01 6.51511487e-01 2.28825247e-01
  2.31529465e-01 2.90672657e-01]
 [1.59007888e-01 4.76269722e-01 9.79695818e-01 9.04992301e-01
  6.64304227e-01 2.25629071e-01 4.18692163e-02 8.95166097e-01
  2.58955685e-01 5.36434046e-01]
 [1.88352379e-01 3.28804610e-01 1.22885146e-01 1.85381368e-01
  6.45610035e-01 3.41634418e-01 3.14742360e-02 4.26608484e-01
  7.57503598e-02 4.21639486e-01]
 [9.94999063e-01 9.08944593e-01 6.45919251e-01 3.70536142e-01
  6.21358865e-01 6.96214453e-01 2.18418908e-01 4.83210303e-01
  8.31791379e-01 8.40153762e-01]
 [5.83351569e-01 3.75871926e-01 1.54762818e-01 6.35824236e

In [22]:
X + Y

array([[0.90175601, 0.70745232, 0.57250375, 0.99819516, 1.64997835,
        0.97013285, 0.95677015, 1.13788026, 0.84742603, 0.66860825],
       [0.15277854, 1.4457264 , 0.51389837, 1.11212046, 1.02816881,
        1.59398807, 1.13732366, 0.93391888, 1.18923512, 0.60998097],
       [0.9664508 , 1.14228257, 0.59423137, 1.0204454 , 1.52680595,
        1.47018249, 1.3879164 , 0.43596578, 1.0254144 , 0.73698816],
       [0.17918639, 1.15550928, 1.33890878, 1.04092098, 1.40151438,
        0.93351064, 0.77827413, 1.10230663, 1.05284062, 0.98274955],
       [0.20853088, 1.00804417, 0.48209811, 0.32131005, 1.38282019,
        1.04951599, 0.76787915, 0.63374902, 0.86963529, 0.86795499],
       [1.01517757, 1.58818415, 1.00513221, 0.50646482, 1.35856902,
        1.40409603, 0.95482382, 0.69035084, 1.62567631, 1.28646927],
       [0.60353007, 1.05511148, 0.51397578, 0.77175292, 1.0146085 ,
        0.76294763, 1.1377655 , 0.63520228, 0.91409975, 1.37788468],
       [0.82358289, 1.13407567, 0.9317942

In [26]:
x = np.random.random((32,))
y = np.random.random((32,))

x @ y

np.float64(8.38806686382907)

In [37]:
def naive_vector_product(x, y):
    print(len(x.shape))
    assert len(x.shape) == 1    
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

naive_vector_product(x, y)

1


np.float64(8.388066863829069)

In [40]:
# Nive matrix multiplication

def naive_matrix_product(X, Y):
    assert len(X.shape) == 2
    assert len(Y.shape) == 2
    assert X.shape[1] == Y.shape[0]
    Z = np.zeros((X.shape[0], Y.shape[1]))
    for i in range(X.shape[0]):
        for j in range(Y.shape[1]):
            Z[i, j] = np.sum(X[i, :] * Y[:, j])
    return Z

X = np.random.random((32, 10))
Y = np.random.random((10, 10))
naive_matrix_product(X, Y)

array([[2.11684208, 3.6899555 , 1.96277126, 2.98211324, 3.44177186,
        3.938806  , 3.49962278, 3.09869157, 3.52521426, 3.65714354],
       [1.82402109, 2.66269693, 2.19506253, 2.27312135, 2.22697267,
        2.95371512, 2.50513509, 2.27750486, 2.6264042 , 2.24323412],
       [1.47358359, 2.83011015, 1.43040457, 2.14982613, 2.64756967,
        3.2453784 , 2.50874509, 2.3852006 , 2.20186847, 2.63237429],
       [1.61167094, 2.68206975, 1.62665109, 2.23100107, 2.60062529,
        3.64035123, 2.30264781, 2.18392235, 2.55197052, 2.58509042],
       [1.81362474, 2.67893137, 2.00466046, 2.60870982, 2.16369952,
        2.81943699, 2.78759516, 1.99048952, 2.599764  , 2.23437607],
       [1.73883973, 3.03347165, 1.92581687, 2.61053311, 2.12689032,
        3.59293756, 2.85194667, 2.2053232 , 2.62526673, 2.22714155],
       [1.42702305, 2.87804709, 1.95718789, 2.0647968 , 1.48177491,
        2.61422645, 2.1153024 , 2.34337332, 2.67589221, 2.29963849],
       [1.55044345, 1.8763617 , 2.0465238

In [41]:
X @ Y

array([[2.11684208, 3.6899555 , 1.96277126, 2.98211324, 3.44177186,
        3.938806  , 3.49962278, 3.09869157, 3.52521426, 3.65714354],
       [1.82402109, 2.66269693, 2.19506253, 2.27312135, 2.22697267,
        2.95371512, 2.50513509, 2.27750486, 2.6264042 , 2.24323412],
       [1.47358359, 2.83011015, 1.43040457, 2.14982613, 2.64756967,
        3.2453784 , 2.50874509, 2.3852006 , 2.20186847, 2.63237429],
       [1.61167094, 2.68206975, 1.62665109, 2.23100107, 2.60062529,
        3.64035123, 2.30264781, 2.18392235, 2.55197052, 2.58509042],
       [1.81362474, 2.67893137, 2.00466046, 2.60870982, 2.16369952,
        2.81943699, 2.78759516, 1.99048952, 2.599764  , 2.23437607],
       [1.73883973, 3.03347165, 1.92581687, 2.61053311, 2.12689032,
        3.59293756, 2.85194667, 2.2053232 , 2.62526673, 2.22714155],
       [1.42702305, 2.87804709, 1.95718789, 2.0647968 , 1.48177491,
        2.61422645, 2.1153024 , 2.34337332, 2.67589221, 2.29963849],
       [1.55044345, 1.8763617 , 2.0465238

In [49]:
a = np.random.random((32))
a.shape
a

array([0.3887498 , 0.10864089, 0.87792242, 0.50564204, 0.73876895,
       0.24211278, 0.69435977, 0.55744558, 0.6252883 , 0.83395058,
       0.18550423, 0.04734756, 0.1142934 , 0.4425583 , 0.8682542 ,
       0.98264637, 0.90561843, 0.63781225, 0.59761328, 0.82277318,
       0.57336396, 0.10202721, 0.44128125, 0.12432223, 0.14036616,
       0.85000403, 0.40205795, 0.44600965, 0.15141718, 0.262361  ,
       0.42347561, 0.29852189])

In [50]:
a = np.expand_dims(a, axis=0)
a.shape

(1, 32)

In [51]:
a

array([[0.3887498 , 0.10864089, 0.87792242, 0.50564204, 0.73876895,
        0.24211278, 0.69435977, 0.55744558, 0.6252883 , 0.83395058,
        0.18550423, 0.04734756, 0.1142934 , 0.4425583 , 0.8682542 ,
        0.98264637, 0.90561843, 0.63781225, 0.59761328, 0.82277318,
        0.57336396, 0.10202721, 0.44128125, 0.12432223, 0.14036616,
        0.85000403, 0.40205795, 0.44600965, 0.15141718, 0.262361  ,
        0.42347561, 0.29852189]])

In [53]:
x = np.random.randint(0, 10, (3, 2))
x.shape, x


((3, 2),
 array([[8, 2],
        [2, 8],
        [9, 3]]))

In [56]:
x.reshape(1, 6), x.reshape(6, 1).shape

(array([[8, 2, 2, 8, 9, 3]]), (6, 1))

In [57]:
x.reshape(6,), x.reshape(6,).shape

(array([8, 2, 2, 8, 9, 3]), (6,))

## First Example

In [59]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Load the dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

x_train = x_train.reshape((60000, 28 * 28))
x_train = train_images / 255.0

x_test = x_test.reshape((10000, 28 * 28))
x_test = x_test / 255.0


model = keras.Sequential([
                            layers.Dense(units=512, activation='relu'),
                            layers.Dense(units=10, activation='softmax')
                        ])

model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5, batch_size=128)




ModuleNotFoundError: No module named 'tensorflow'